name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore StackYenoDeobfuscator.sln
    
    - name: Build solution
      run: msbuild StackYenoDeobfuscator.sln -t:rebuild -property:Configuration=Release -property:AllowUnsafeBlocks=True

    - uses: actions/upload-artifact@v3
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      with:
        name: StackYenoDeobfuscator
        path: StackYenoDeobfuscator/bin/
